#!groovy

// Generated by IBM TransformationAdvisor
// Thu Feb 07 10:09:09 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}